In [3]:
import pandas as pd
#Dataset for the Task: "titanic.csv"
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datasets/Titanic-Dataset.csv")

3.1 Warm Up Exercises:
1. Sorting and Subsetting:

In [5]:
# 1 - Sorting:
#1.Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the head of the result.
fare = df['Fare']
fare.head()

#2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
class_age = df[['Pclass', 'Age']]
print(class_age.head())
#3.Create a DataFrame called survived gender that contains the Survived and Sex columns of the
#Titanic dataset, in that order.Print the head of the result.
survived_sex = df[['Survived', 'Sex']]
survived_sex.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

Problem - 2 - Subsetting:

In [6]:
#1.Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it to fare gt 100.View the printed result.
fare_gt_100 = df[df['Fare'] > 100]
print("the passenger fare is greater than 100 are : \n");
fare_gt_100.head()
#2.Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to first class.View the printed result.
first_class=df[df['Pclass']==1]
print(" passenger’s class (Pclass) is 1 are : \n")
first_class.head()
#3.Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
#is female (Sex is "female"), assigning it to female under 18. View the printed result.
female_under_18 = df[(df['Age'] < 18) & (df['Sex'] == 'female')]
female_under_18.head()

the passenger fare is greater than 100 are :

 passenger’s class (Pclass) is 1 are :

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

Subsetting Rows by Categorical variables:

In [7]:
  #Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"(Southampton), assigning the result to embarked c or s. View the printed result.
  embarked_c_or_s = df[(df['Embarked'] == 'C') | (df['Embarked'] == 'S')]
  embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
#Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating firstor second class), assigning the result to first second class.View the printed result.
first_second_class = df[df['Pclass'].isin([1, 2])]
first_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

3.2 Exploratory Data Analysis Practice Exercise - 1.

Which passenger had the highest fare paid relative to their age?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).
2. Subset rows where fare per year is higher than 5, assigning this to high fare age.
3. Sort high fare age by descending fare per year, assigning this to high fare age srt.
4. Select only the Name and fare per year columns of high fare age srt and save the result as result.
5. Look at the result.

In [9]:
# Fill missing Age values with the median age
df['Age'].fillna(df['Age'].median(), inplace=True)

# Calculate fare per year of age
df['fare_per_age'] = df['Fare'] / df['Age']

# Filter rows with fare per age greater than 5
filtered_df = df[df['fare_per_age'] > 5]

# Sort filtered rows by fare_per_age in descending order
sorted_df = filtered_df.sort_values(by=['fare_per_age'], ascending=False)

# Select Name and fare_per_age columns
final_result = sorted_df[['Name', 'fare_per_age']]

# Display the first few rows
final_result.head()

<ipython-input-9-a8380be2969d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

                                Name  fare_per_age
305   Allison, Master. Hudson Trevor    164.728261
297     Allison, Miss. Helen Loraine     75.775000
386  Goodwin, Master. Sidney Leonard     46.900000
164     Panula, Master. Eino Viljami     39.687500
183        Becker, Master. Richard F     39.000000

Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.
2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.
3. Sort adult males by descending fare per class, assigning this to adult males srt.
4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.

In [10]:
# Calculate fare per class
df['fare_by_class'] = df['Fare'] / df['Pclass']

# Filter adult males
males_adults = df[(df['Sex'] == 'male') & (df['Age'] >= 18)]

# Sort adult males by fare_by_class in descending order
sorted_males = males_adults.sort_values(by=['fare_by_class'], ascending=False)

# Select Name, Age, and fare_by_class columns
final_result = sorted_males[['Name', 'Age', 'fare_by_class']]

# Display the first few rows
final_result.head()

                                   Name   Age  fare_by_class
737              Lesurer, Mr. Gustave J  35.0       512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0       512.3292
438                   Fortune, Mr. Mark  64.0       263.0000
27       Fortune, Mr. Charles Alexander  19.0       263.0000
118            Baxter, Mr. Quigg Edmond  24.0       247.5208

3.3 Exploratory Data Analysis with Group-by Method Practice Exercise:

Based on the dataset Answer the following question:
What percent of the total fare revenue came from each passenger class?
To answer the question perform following operation:
1. Calculate the total Fare paid across all passengers in the Titanic dataset.
2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.
3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).
4. Combine the fare totals from first, second, and third classes into a list.
5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.

In [11]:
# Calculate total fare revenue
total_revenue = df['Fare'].sum()

# Calculate fare revenue by class
fare_first = df[df['Pclass'] == 1]['Fare'].sum()
fare_second = df[df['Pclass'] == 2]['Fare'].sum()
fare_third = df[df['Pclass'] == 3]['Fare'].sum()

# Store class fares and calculate their proportions
fares_by_class = [fare_first, fare_second, fare_third]
fare_percentages = [(fare / total_revenue) * 100 for fare in fares_by_class]

# Display results
print("Fare revenue percentages by class:")
print("First Class: {:.2f}%".format(fare_percentages[0]))
print("Second Class: {:.2f}%".format(fare_percentages[1]))
print("Third Class: {:.2f}%".format(fare_percentages[2]))

Fare revenue percentages by class:
First Class: 63.35%
Second Class: 13.25%
Third Class: 23.40%

Based on the dataset Answer the following question:
What percent of the total number of passengers on the Titanic belonged to each age group
(e.g., child, adult, senior)?
To answer the question perform following operation:
1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18{64), and "senior" (age 65 and above).
2. Calculate the total number of passengers on the Titanic.
3. Count the number of passengers in each age group.
4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.
5. Display the proportion as a percentage.

In [12]:
# Create an age group column
df['age_category'] = pd.cut(df['Age'], bins=[0, 18, 65, float('inf')], labels=['child', 'adult', 'senior'])

# Calculate total passengers
passenger_count = len(df)

# Count passengers in each age group and calculate proportions
group_counts = df['age_category'].value_counts()
group_percentages = (group_counts / passenger_count) * 100

# Display the proportions
print("Passenger percentages by age group:")
print(group_percentages)

Passenger percentages by age group:
age_category
adult     83.501684
child     15.600449
senior     0.897868
Name: count, dtype: float64